name: CI - Testes Automatizados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup do Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache do Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build com Maven
      run: mvn clean install

    - name: Rodar os testes
      run: mvn test

    - name: Gerar relatório Allure
      run: mvn allure:serve
      continue-on-error: true

    - name: Upload do relatório Allure
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-results
